## Pandas - DataFrame and Series

It is widely used for data manipulation, data analysis and data cleaning.It provides two primary data structure:Series and DataFrame.

SERIES - It is a 1-d array like object.

DATAFRAME - It is a 2-d ,size-mutable,and potentially heterogenous tabular data structure with labeled axes(rows and columns).

In [4]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\anudip\onedrive\desktop\data analysis\env\lib\site-packages (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\anudip\onedrive\desktop\data analysis\env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\anudip\onedrive\desktop\data analysis\env\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\anudip\onedrive\desktop\data analysis\env\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: numpy>=1.22.4 in c:\users\anudip\onedrive\desktop\data analysis\env\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: six>=1.5 in c:\users\anudip\onedrive\desktop\data analysis\env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

WARNING: You are using pip version 21.2.3; however, version 25.1.1 is available.
You should consider upgrading via the 'C:\Users\Anudip\OneDrive\Desktop\Data Analysis\env\Scripts\python.exe -m pip install --upgrade pip' command.

In [5]:
import pandas as pd

In [6]:
## Series 
## Pandas Series is a 1-d array like object that can hold any data type.It is similar to a column in a table.

import pandas as pd 
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [7]:
## Create a serirs from dictionary

data={'a': 1,'b':2,'c':3,'d':4}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
d    4
dtype: int64

In [8]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [ ]:
## DataFrame
## It is similar to a table in a database

## Create a Dataframe from a dictionary of list

data={
    'Name':['Krish','John','Jack'],
    'Age' :[25,30,45],
    'City' :['Banglore','New York','Florida']
}

df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      City
0  Krish   25  Banglore
1   John   30  New York
2   Jack   45   Florida
<class 'pandas.core.frame.DataFrame'>

In [10]:
import numpy as np
np.array(df)

array([['Krish', 25, 'Banglore'],
       ['John', 30, 'New York'],
       ['Jack', 45, 'Florida']], dtype=object)

In [13]:
### Create a Data Frame from a list of dictionaries 

data =[
   {'Name':'Krish','Age':32,'City':'Banglore'},
   {'Name':'John','Age':34,'City':'Banglore'},
   {'Name':'Bappy','Age':32,'City':'Banglore'},
   {'Name':'Jack','Age':32,'City':'Banglore'}
    ]

df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      City
0  Krish   32  Banglore
1   John   34  Banglore
2  Bappy   32  Banglore
3   Jack   32  Banglore
<class 'pandas.core.frame.DataFrame'>

In [63]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [66]:
# Display the data types of each column 
print("Data types: \n", df.dtypes)

# Describe the DatFrame
print("Statistical summary :\n",df.describe())

Data types:
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object
Statistical summary :
        Transaction ID  Units Sold   Unit Price  Total Revenue
count        10.00000   10.000000    10.000000      10.000000
mean      10005.50000    2.700000   492.190000     730.573000
std           3.02765    1.766981   778.911177     880.368706
min       10001.00000    1.000000    15.990000      51.980000
25%       10003.25000    1.250000    39.990000     104.980000
50%       10005.50000    2.000000    89.990000     354.980000
75%       10007.75000    3.750000   574.990000    1034.970000
max       10010.00000    6.000000  2499.990000    2499.990000

In [67]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count        10.00000   10.000000    10.000000      10.000000
mean      10005.50000    2.700000   492.190000     730.573000
std           3.02765    1.766981   778.911177     880.368706
min       10001.00000    1.000000    15.990000      51.980000
25%       10003.25000    1.250000    39.990000     104.980000
50%       10005.50000    2.000000    89.990000     354.980000
75%       10007.75000    3.750000   574.990000    1034.970000
max       10010.00000    6.000000  2499.990000    2499.990000

In [23]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
5,10006,2024-01-06,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card
6,10007,2024-01-07,Electronics,MacBook Pro 16-inch,1,2499.99,2499.99,North America,Credit Card
7,10008,2024-01-08,Home Appliances,Blueair Classic 480i,2,599.99,1199.98,Europe,PayPal
8,10009,2024-01-09,Clothing,Nike Air Force 1,6,89.99,539.94,Asia,Debit Card
9,10010,2024-01-10,Books,Dune by Frank Herbert,2,25.99,51.98,North America,Credit Card

In [25]:
data={
    'Name':['Krish','John','Jack'],
    'Age' :[25,30,45],
    'City' :['Banglore','New York','Florida']
}

df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      City
0  Krish   25  Banglore
1   John   30  New York
2   Jack   45   Florida
<class 'pandas.core.frame.DataFrame'>

In [26]:
### Accessing data from DaaFrame

data

{'Name': ['Krish', 'John', 'Jack'],
 'Age': [25, 30, 45],
 'City': ['Banglore', 'New York', 'Florida']}

In [28]:
df

    Name  Age      City
0  Krish   25  Banglore
1   John   30  New York
2   Jack   45   Florida

In [31]:
df['Name']

0    Krish
1     John
2     Jack
Name: Name, dtype: object

In [32]:
type(df['Name'])

pandas.core.series.Series

In [33]:
df.loc[0]

Name       Krish
Age           25
City    Banglore
Name: 0, dtype: object

In [35]:
df.iloc[0]

Name       Krish
Age           25
City    Banglore
Name: 0, dtype: object

In [37]:
df.iloc[0][0]

C:\Users\Anudip\AppData\Local\Temp\ipykernel_11100\2900375399.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

'Krish'

In [38]:
df.iloc[0][1]

C:\Users\Anudip\AppData\Local\Temp\ipykernel_11100\2309508539.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][1]

np.int64(25)

In [39]:
df.iloc[0][2]

C:\Users\Anudip\AppData\Local\Temp\ipykernel_11100\2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]

'Banglore'

In [41]:
## Accessing A specified element

df['Name']

0    Krish
1     John
2     Jack
Name: Name, dtype: object

In [42]:
df

    Name  Age      City
0  Krish   25  Banglore
1   John   30  New York
2   Jack   45   Florida

In [43]:
df.at[1,'Age']

np.int64(30)

In [44]:
df.at[2,'Age']

np.int64(45)

In [45]:
## Accessing a specified element using iat
df.iat[2,2]

'Florida'

In [46]:
## Data Manipulation with DatfRAME

df

    Name  Age      City
0  Krish   25  Banglore
1   John   30  New York
2   Jack   45   Florida

In [ ]:
## Adding a column
df['Salary']=[50000,60000,70000]
df

    Name  Age      City  Salary
0  Krish   25  Banglore   50000
1   John   30  New York   60000
2   Jack   45   Florida   70000

In [54]:
## Remove  a column 
df.drop('Salary', axis=1,inplace=True)

In [55]:
df

    Name  Age      City
0  Krish   25  Banglore
1   John   30  New York
2   Jack   45   Florida

In [56]:
## Add age to the column 
df['Age']=df['Age']+1
df

    Name  Age      City
0  Krish   26  Banglore
1   John   31  New York
2   Jack   46   Florida

In [58]:
df.drop(0,inplace=True)